<?php
/**
 * PinStatusTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  NFTStorage
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * NFT Storage API
 *
 * # API Reference
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.1.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace NFTStorage\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * PinStatusTest Class Doc Comment
 *
 * @category    Class
 * @description PinStatus
 * @package     NFTStorage
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class PinStatusTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PinStatus"
     */
    public function testPinStatus()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
